### ISSUE TITLE
Running `./gradlew mkdocsPublish` in parent project results in submodules overwriting parent module.

### ISSUE THREAD

**Issue by michael-newsrx** [xvik/gradle-mkdocs-plugin#42] opened 2022-08-02 14:03 UTC
Parent project is configured for mkdocs.

Parent project has one or more submodules.

If any submodule is separately configured for mkdocs.

Running `/.gradlew mkdocsPublish` results in the submodule `mkdocsPublish` task overwriting the parent's `mkdocs` output.

**Comment by xvik** [comment] 2022-08-04 08:40
Thank you for the report! 
I tried to reproduce this and did not note any overrides.

Maybe you were publishing into the same git repository and target doc folders for root and submodule were named the same and that cause the override you refer to:
1. Root build docs in folder 'build/mkdocs/1.0`
2. Module (for example, named 'sub') build docs in folder 'sub/build/mkdiocs/1.0'
3. Root pushed folder '1.0' into git
4. Submodule pushed its '1.0' folder and override root docs

If that was the case and you need to push both folders into the same git (same branch) then rename root or submodule folder, for example:

```
mkdocs.publish.docPath = 'sub-\$version'
```

In this case two separate folders would be published: '1.0' and 'sub-1.0'.

It is also importatnt to disable root redirects in one of modules:
`mkdocs.publish.rootRedirect = false` 
because only one folder could be the default.

If your case is different, please describe it so I can reproduce.

**Comment by michael-newsrx** [comment] 2022-08-04 11:56
It's not an override. It's an overwrite.

Submodule builds use the same build folder as the parent build when built from the parent.

When I run `./gradlew mkdocsBuild` in the parent project each submodule clears out the `build/mkdocs` folder and then places it's output there. This is because the submodules get the same working directory for builds as the parent module. I'm not sure there is an easy fix other than documenting that you have to use `./gradlew :mkdocsBuild` and not `./gradlew mkdocsBuild`.

**Comment by xvik** [comment] 2022-08-04 12:18
Can you please post mkdocs-related configurations (if it happens inside allprojects or subprojects block, please mention it)?

I checked with mostly default settings and it was working:

```
          mkdocs {
                sourcesDir = 'docs'
          }
          
          project(':doc') {
              apply plugin: 'ru.vyarus.mkdocs' 
              
              mkdocs {
                  sourcesDir = 'src'
                  
                  publish {
                      docPath = 'sub-$version'
                      rootRedirect = false
                  }
              }
          }
```

There should be something in your config causing overwrites (could be side effects of allprojects/subprojects block usage). 
Build dir is declared in `mkdocs.buildDir` and resolved using context project, so build dirs should be different.

**Comment by xvik** [comment] 2022-08-11 09:31
Did you solve your problem? In case if not, without configuration example I wouldn't be able to help (I can't reproduce).

**Comment by michael-newsrx** [comment] 2022-08-11 18:06
Sorry, I've been swamped. Will try and put together something today.

**Comment by xvik** [comment] 2022-11-01 14:04
Closing this as not active, but please reopen if you still have this problem and can describe how it could be reproduced

**Closed by xvik** 2022-11-01 14:04 UTC
